### ISSUE TITLE
icon bar not showing up

### ISSUE THREAD

**Issue by yarmenti** [voila-dashboards/voila-vuetify#26]
Hi, it's me again!

As I don't have access to git with my professional computer, I'm not able to make pull requests.
Thus, in app.html, one must change:
`<v-toolbar-side-icon>` to `<v-app-bar-nav-icon>`
as Vuetify version used is 2.x. Indeed, the icon button is not showed using the dashboard as is.

Yannick

**Comment by mariobuikhuizen** [comment]
Hi Yannick,

Thanks for reporting this issue, but it has already been reported in #22, fixed and released as v0.2.1.

**Comment by yarmenti** [comment]
Thank you!
