### ISSUE TITLE
Another clipping issue

### ISSUE THREAD

**Issue by SylvainCorlay** [voila-dashboards/voila-vuetify#28]
I think that the left sidebar should be over the topbar when activated:

![Screenshot from 2019-12-16 12-43-33](https://user-images.githubusercontent.com/2397974/70904561-fecb1680-2001-11ea-9525-a27a2cb4c39f.png)

**Comment by mariobuikhuizen** [comment]
Thanks for reporting this issue.

I will also fix #24 and then make a new release.
