### ISSUE TITLE
Make sidepane customizable

### ISSUE THREAD

**Issue by martinRenou** [voila-dashboards/voila-vuetify#30]
The default template uses a hardcoded sidepane, it would be super nice if the sidepane was provided by the user in their Notebook.

I can try to come up with a PR.

**Comment by mariobuikhuizen** [comment]
The content of the side pane is already overridable by providing a widget with mount_id: "content-nav". Do you want access to a higher level in the side pane?

**Comment by martinRenou** [comment]
I guess that answers my question, thanks Mario.
