### ISSUE TITLE
MDI dependency

### ISSUE THREAD

**Issue by guimillet** [voila-dashboards/voila-vuetify#53]
The [base template](https://github.com/voila-dashboards/voila-vuetify/blob/4cb4186a2f8cbf197463fcbdd0c78ef54c9fe4b6/share/jupyter/nbconvert/templates/vuetify-base/index.html.j2#L9) downloads a Material Design Icons CSS with a version 4.4.95 but ipyvuetify seems to rely on more recent versions, which ends up in some icons missing when rendering with voila-vuetify templates.

Ipyvuetify has two (is it an error?) dependencies related to mdi in [js/package.json](https://github.com/mariobuikhuizen/ipyvuetify/blob/898a2668e1773701881252e6f96e30ef3cb436f0/js/package.json#L60):
```
    "@mdi/font": "^4.9.95",
    "material-design-icons-iconfont": "^5.0.1",
```
It seems appropriate to maintain a same version of MDI between ipyvuetify and voila-vuetify.

**Comment by mariobuikhuizen** [comment]
Ah, I overlooked the change in the middle version number from `4` to `9`, thanks for pointing this out.
